// Problem: Print the pattern (Solid Rectange). 1
//                                              0 1
//                                              1 0 1
//                                              0 1 0 1
//                                              1 0 1 0 1
// Solution: Used nested 'for' loops. The pattern is generated by calculating 
// the sum of row and column indices (i + j). If the sum is even, '1' is 
// printed; otherwise, '0' is printed, creating the alternating 0-1 structure.

public class Problem_9 {
  public static void main(String[]args) {
    // For rows
    int n = 5;

    //Outer loop: Outer loop: iterates through each row
    for(int i=1; i<=n; i++){

        //Inner loop: iterates through each column in the current row
        for(int j=1; j<=i; j++){
            int sum = i + j;
            if(sum % 2 == 0){
                System.out.print("1" + " ");
            }
            else{
                System.out.print("0" + " ");
            }

        }
        // Move to the next line after printing each row
        System.out.println();        
    }
    }
}